### ISSUE TITLE
Overarching Deckbuilder Gameplay Ideas

### ISSUE THREAD

**Issue by firstlane** [dokidzung/32BitJam#32]
Alan and I were discussing how UI components of the game could overlap, such as placing the deckbuilder UI layer over the top-down layer when the player wants to access their cards.

Out of this discussion, we had a couple ideas for the deckbuilder which we wanted to bring up here.

### Deckbuilder Ideas
1. Restrict the number of cards that can be held.
2. Have permanent and temporary cards.
    - Permanent cards would be acquired through defeating bosses and completing main objectives.
    - Temporary cards could be picked up in a level to help boost the character for a certain amount of time. Alternatively, they could be held (up to a certain number) and used later in the dating sim to help level up your relationship with your permanent cards.

I'd like to get more input on this.

### Side Note
Also, I think it might make sense going forward to have larger design discussions on GitHub rather than on Discord. It's easier to lose things on Discord, where here everything can be tied to an issue, and discussion on an issue here will probably be more detailed due to the format. Do we want to commit to that?

**Comment by dokidzung** [comment]
I think we can move this discussion over to the discussion tab just so our issue backlog doesn't get cluttered

**Comment by firstlane** [comment]
I did not know GitHub had a discussions tab lol
